package mcp

// portingRule says where one part of a document goes in Cartograph, or
// that it stays out, and how: so an agent porting a plan, a charter or a
// strategy never has to decide what the discipline already has.
type portingRule struct {
	Part string `json:"part"`
	Goes string `json:"goes"`
	How  string `json:"how"`
}

// porting is the map taxonomy returns beside the kinds. Each rule settles
// a question an agent porting a real charter had to judge, and names only
// fields the schemas hold.
var porting = []portingRule{
	// Asking the person.
	{"A fact the document does not give, or defers (a target set later, a score nobody made)", "Ask your person, as soon as a check needs it", "Ask in the document's own words, the full term with what it means the first time (\"intake graders, the members who grade produce as it reaches a depot\"), not Cartograph's kind names. Say why you ask (what the document says or leaves out, and which check waits on it) and offer the options you can draw from it; take their answer. Where this map says to leave a check open, that is for when they cannot answer yet: leave_open with their answer as asked."},

	// Working without the person.
	{"Your person is not there to ask", "Work from the documents alone, and skip asking how they want to work", "Port what they state; leave_open each check only your person can answer, with the reason. Never invent a fact to meet a check. Where this map gives a default, take it and do not leave the check open."},
	{"A check that fails only because of a fact already left open", "leave_open, listing it in also", "One leave_open with also covers the checks the same missing fact fails (a target left open fails smart-measurable and smart-time-bound on the aims it measures). Two facts behind one check: leave it open twice; both reasons are kept."},

	// Whose record, and its purpose.
	{"The organisation", "Purpose.organisation (id default)", "The organisation whose work the document is: usually the body that issues it. An umbrella it reports to (a cluster, a parent department) is not it: record that as a governance body if it decides on the work or gives it direction (when it does so through a committee, the committee is the body, and the umbrella goes in the source), else add it to the purpose's source after the document, as \"<document>; within <umbrella>\". The organisation itself is not a Team: its units are Teams with no parent unless the document gives their hierarchy."},
	{"Vision and mission", "Purpose.vision, Purpose.mission", "From the organisation's own documents. When none gives them, leave purpose-vision and purpose-mission open for your person with leave_open; never write your own. A goal's smart-relevant then waits on them with the same reason, by itself. Purpose.source names where they are published, or the document you ported from when they are left open."},
	{"A project or document identifier (\"Project ID\")", "metadata.alias", "As written. The document's version, classification and approval status are document control: not ported."},

	// The aim tree.
	{"Long-term impact", "Goal, level goal", "The lasting change the organisation pursues."},
	{"Intended outcome of a programme or project", "Goal, level objective, under the goal it serves", "One objective; the work's own outcomes sit under it."},
	{"A logic model's outcomes column", "Goal, level outcome, under the objective", "Each clause of the column (split at semicolons or bullets) is one outcome: a state that is true once it is reached, not an activity."},
	{"A logic model's inputs, activities and outputs", "Inputs: the project's resources and funding. Activities: tasks. Outputs: deliverables", "The outcomes column is the aim tree's (see above)."},
	{"The document's own wording of an aim", "Goal.statedAs, verbatim; Goal.objective in the level's form", "objective is rewritten to the level (an action and its result for a goal, a change for an objective, a state for an outcome) within its length; statedAs keeps the document's sentence as written."},
	{"A goal that is standing policy with no end date", "Goal.horizon ends at its next review", "Start: the month the decision that set the policy was issued. End: the year the document says it is reviewed; a review in an academic or financial year written as two years (2028/2029) ends in the later one. With no review stated, leave the horizon check open for your person."},
	{"An objective's or outcome's horizon", "Left unset: it inherits the horizon above it", "Set one only when the document dates that aim itself; with only an end dated, the start is the start of the horizon above it."},
	{"An objective's or outcome's whyItMatters", "The sentence of the document's rationale or problem it answers, shortened", "One sentence; the problem statement is the fallback."},
	{"Two wordings of the same aim", "statedAs: the one in the body of the document, not a summary or canvas", "Cite that section as the source."},
	{"A review that decides whether the policy continues", "The goal's horizon end", "What it decides goes in the project's notes under the step key goals."},
	{"Pilot or proof-of-concept results", "A Gap where they show a shortfall; an Assumption's testedBy where they test a belief; else the notes of the step the choice they informed sits in", "Goal.evidence is filled by the editor, never written by you."},
	{"A project's own objectives", "Project.objectives: exactly one", "The change the project exists to make, then how, in one sentence. A document's list of several objectives is usually its components' work: each that is a strand with its own lead, dates or risks is the objective of a component (see below); each that is a measurable result of the main change is a key result of the one objective. Keep the document's wording in the notes under the step key measures."},
	{"A number inside a name (\"Grade 1\", \"Memo 17\")", "Kept in the statement as written", "Only a number that is a target belongs in a key result. A date or a term (\"by July 2027\", \"in Term I 2026/2027\") is not in an objective: it is the key result's target date or the timeline's. A count that sizes the scope (\"the 112-site frame\") goes in scopeIn or the description, not the objective."},
	{"A project with components", "Key results on the parent's objectives that the components add up to", "The development objective's indicators: what the components achieve together, such as the share of sites where the change is in place. They may repeat an aim's key result when the aim and the project are measured by the same indicator; better still, name that indicator's KPI under kpis."},
	{"A key performance indicator register", "KPI, each with its owner and cycle; the project names it under kpis", "A measure that is already a KPI is named in the project's kpis with a reason, never restated as a key result. A key result is a measure only this project reaches for."},
	{"A measure taken once", "A success criterion read at closing, or a deliverable's acceptance", "Not a KPI: an indicator is read on a cycle. Collecting a baseline is a deliverable, and a criterion saying it was collected is that deliverable's acceptance. A criterion that the baseline was used to set targets is compliance (a decision taken), confirmed by the body that sets them."},
	{"A measure taken once, then on a cycle (\"once, then annual\")", "KPI on that cycle", "The baseline is the document's baseline where it gives one (with several dated values, the latest; the earlier ones are readings), else the first reading."},
	{"A measure read several times within one window (per session, per training cycle, per protocol)", "KPI on a reporting cycle of named periods, one per window the document names", "Each period ends in the month its window ends."},
	{"An impact-level indicator", "KPI with resultLevel impact, goals naming the goal the impact became", "An outcome indicator aligns to its outcome, an output indicator to the objective it serves."},
	{"One indicator read from successive sources", "KPI.sources: one item, the source read now", "The definition says which source takes over, and from when; several items only for a figure computed from several at once. The cycle has a named period for each wave the document dates, from either source. When the next source measures a different population (a cohort or subset counts), it is a second KPI: its baseline unknown with the reason, its target as the document defers it, its cycle the new source's waves."},
	{"An indicator whose unit the document does not state", "KPI.unit: the word for what is counted or scored (score, points, people)", "Say in the definition that the document states no unit. A count and a share both stated (\"n and %\"): percent, the count in the definition. Count or share left open: percent when the document names what it is a share of (\"all X\" is a share of X, target 100), else a count."},
	{"An indicator or target the document defers (\"set after the baseline\")", "The KPI with target left out, kpi-target left open with the reason", "Its aims' smart checks go in the same leave_open's also. A baseline that was measured but whose figure the document does not give: leave kpi-baseline open."},
	{"An outcome with no indicator in the document", "Key results built from the benefits plan row whose benefit is that outcome's state and whose target is a figure", "An output indicator is never repeated as an outcome's key result. With no such row, leave smart-measurable, smart-attainable and smart-time-bound open for your person."},
	{"Past readings of a KPI", "KPIReadings (id <kpi id>-readings) drafted in the change set", "One reading per period, filed by the month its period ends; a year alone is that year's last month."},
	{"A gap, shortfall or problem with evidence", "Gap", "metadata.name: the result that falls short, in a few words. statement: the document's own words, never edited to fit (up to 400 characters; what does not fit goes in note). current and desired: a short sentence each. source: document and section. measure: the KPI that tracks it, when one exists; without one a sourced gap with both states is a complete observation. affects: the beneficiary groups the document says it falls on; a problem that cites the gap names its groups from these, and the two must agree both ways (TAXONOMY.md D45). Where the document does not say who, ask the person."},
	{"Where the evidence was found (districts, regions, kinds of site)", "Segment, the dimension first then its values", "Only the values the document names. A data source's category from its own word for the store: database or dataset is database, survey or form is formOrSurvey, records or file is paperRecord unless it says electronic, portal or system is operationalSystem, spreadsheet is spreadsheet; a survey known by its name alone (GSHS) is formOrSurvey. Two names for the same records are one source. A dimension with no named values is recorded as the dimension. When the document names values without their dimension (two islands), name the dimension by what varies (Island); a place named beside unnamed values of a finer dimension (\"seven districts and Tobago\") is a value of the coarser one. \"All\" in a target is 100 percent."},
	{"Citing a gap that names segments", "The citation's segments: every segment the work reaches", "All of them when the work reaches every one; left empty only for a gap that names none. When you add segments to a gap, name them again on every citation of it."},
	{"Evidence of the long-term impact (a trend in the population the goal is about)", "The impact KPI's readings (KPIReadings), and the goal's whyItMatters", "Not a Gap: a gap closes into an outcome, and the impact is the goal's."},
	{"A KPI register's baseline cell used as evidence (\"0\", \"Pilot cohort only\")", "Gap: name the shortfall in results, in words; statement quotes the cell with its row, as \"<indicator>: <cell>\"", "Only for rows ported as KPIs; a row ported as a deliverable is no gap. current is the cell in a sentence, desired the register's target; source the register and row."},
	{"An undated baseline cell (\"0\", \"None\")", "The baseline value, dated the document's date", "\"None\" is 0 when the indicator counts something; otherwise unknown with the reason."},
	{"A target that is a milestone (\"collected in Term I\", \"published\")", "Not a KPI target: a deliverable with its acceptance", "The register row is ported as that deliverable, not as a KPI, even when its frequency says \"once, then annual\". A benefits row whose target is a milestone is that deliverable's acceptance too, never a key result."},
	{"An outcome the document gives no shortfall for", "No Gap; leave closes-gap open with the reason", "Never build a gap the document does not evidence."},
	{"A gap whose evidence covers every value of a dimension (national evidence)", "segments: every value of the dimension the work is planned by", "When the document names no values of that dimension, every value of the first dimension whose values it does name. When it names none at all, or the gap is about a thing not divided that way (products, a list), leave gap-segments open, saying so."},

	// Work.
	{"A workstream or strand whose result is an output the project hands over (a handbook, materials, a toolkit, communications, training delivered)", "Deliverables of this project, whoever leads them", "Its lead is the deliverable's owner, not a project manager; its dates are milestones and its risks this project's. Ask whether it would be chartered on its own with an objective that is a change, not an output: if not, it is a deliverable."},
	{"Work with a change of its own that the project depends on (a survey that sets a baseline, a system or portal people will use, an app, a study), or that another body runs to its own plan", "A Project of its own, listed in the parent's components", "Whoever leads it, inside the organisation or not. Write it as a project in its own right: one objective (the change its work makes), its problem (the part of the parent's problem it answers, in the parent's words), scope, deliverables, milestones, risks, costs and manager, all moved from the parent. The parent lists it under components with why it depends on it. A milestone that waits on another project's milestone names it: event on {kind: Project, id} with item. Write components before the parent, deepest first, so each names only what exists."},
	{"What stays with the parent", "Its one objective, its own deliverables and milestones, its components", "The parent's objective is the document's intended project outcome, as a change; its key results are what the components together achieve. Coordination, governance and reporting stay the parent's own work, never a component. A strand that needs its own sponsor or budget is still a component: a component is any project another depends on."},
	{"A project's problems", "One problem per beneficiary group the document says the situation harms", "A group said only to lack support has no problem of its own. Each cites the gaps it answers, with their segments; a gap about a party that is no group (companies) goes on the problem of the group it reaches through them."},
	{"A workstream that is the project's own management or coordination", "The parent project's own work", "Not a component; what it produces stays among the parent's deliverables."},
	{"A workstream the document puts out of scope, or that runs on another body's budget", "Not a component; a scopeOut line", "Name it in the parent's scopeOut, and as a dependency when the work waits on it."},
	{"Milestones", "Project.milestones, each with its timing, owner and evidence", "Only the milestones still to come, and those a later one waits on. Timing: a date, a window (a term), after another milestone with a lag, or set when an event happens with the month it is expected by. A milestone's name is a few words; never repeat the deliverable's name in it."},
	{"Who accepts a deliverable", "acceptance by: the role the document gives assurance for that kind of output (technical, data, reports)", "Else the component's manager, else the project's. The deliverable register's owner column is the role of its tasks."},
	{"Milestones already completed", "Not ported, unless a milestone still to come waits on one", "That one is ported with an event recording when it was reached. One that authorised the work (a decision, a directive) is a mandate."},
	{"Milestones that are a rule taking effect (\"Term II controls apply\"), and a phased schedule of requirements", "The notes under the step key timeline", "Neither work nor a deliverable; the requirements themselves are the policy's, not the project's. A project objective that only says a rule takes effect, with no deliverable, goes there too."},
	{"Project phases", "A milestone at each phase's end", "A phase is the run of work up to its milestone; never port both."},
	{"Handover requirements (what passes to the service)", "An acceptance line by the service owner's role on the deliverable that produces each item", "A new deliverable of the parent only for an item no deliverable produces; that the service runs with them is a criterion atLanding."},
	{"Success criteria that only say an output was delivered", "That deliverable's acceptance", "A success criterion is the state the outputs are for."},
	{"Success criteria and their dimension", "Project.successCriteria with metric", "efficiency: on time, on budget, to scope, read from the project's own schedule and spend (no source). customer: the beneficiaries use it, gain from it or are satisfied. team: the team's capacity or learning. business: the organisation's own results. future: readiness for what comes next (evidence gathered, a baseline set, capacity built). compliance: a requirement met or not, and a decision taken or not, confirmed by the role or body that takes it. Every criterion has an owner (the role that tracks it: the manager's when the document names none) and confirmedBy (the role or body the document names; else the sponsor's role)."},
	{"A criterion that something was done or communicated, with no deliverable", "compliance", "A requirement met or not."},
	{"Pointing a success criterion at the deliverables behind it", "successCriteria from: {\"local\":\"deliverables\",\"id\":\"<deliverable id>\"}", "Optional; only where a deliverable produces the outcome."},
	{"A benefits realisation plan", "Success criteria judged after closing (postClosingCycle)", "Owned by the owner the plan names (else the service owner's role) and read on a reporting cycle: the one whose periods its review dates fall in; a one-off review is atClosing when it falls before or in the project's last month, atLanding after. A benefit that says what a success criterion already says is that criterion, not a second one, and keeps the criterion's when; embedded in operations is business. Its statuses are progress, not ported."},
	{"Legal, safeguarding, consent, data protection, accessibility, equity or environmental requirements", "Success criteria of metric compliance", "Each confirmed by the role the document says answers for it, else the sponsor's role; personal data also on the data step. \"None identified\" is no criterion."},
	{"Deferred or future scope", "Project.summary.scopeOut, as \"Deferred: ...\"", "And a gap where the document gives evidence for it. Each line up to 60 characters: shorten to the thing, the detail in the notes under the step key scope."},
	{"The people served, and counts of them", "BeneficiaryGroup, named without numbers", "A count that is a measure is a KPI's baseline; a sample size is a data source's quality issue; a headcount the work draws on is planning, not ported."},
	{"A beneficiary that is not a group of people (companies, a public system)", "A StakeholderMap entry as a resource (externalParty or orgUnit)", "Not a BeneficiaryGroup."},

	// Who.
	{"Units of the organisation that carry work", "Team, only for a unit that is some project's, operation's or data source's team", "A unit that only leads or co-leads is an orgUnit Resource."},
	{"A unit that carries work and is named as an owner", "A Team for the work, and an orgUnit Resource of the same name for owner fields", "Owner fields name the unit as an orgUnit Resource (the unit answers as a whole), or the role the document names in it; never invent a head role it does not name. Never a team in an owner field."},
	{"Units the work draws on without carrying it", "Resource, category orgUnit", ""},
	{"Bodies outside the organisation (other ministries, agencies, partners, companies)", "Resource, category externalParty", "Even a sister body inside the same government."},
	{"Committees and boards that decide", "Resource, category governanceBody", "Referenced as a mandate's issuer, who confirms success, whom a risk escalates to, and on the escalation route; never typed as text."},
	{"A decision or note that authorises the work, with no title", "Mandate titled as the document describes it (\"Note dated November 2025\")", "Its issuer is the body that took the decision or noted it, not the one that submitted it. A later decision that only changes the phasing or scope is not a mandate: say it in the notes under the step key timeline or scope. An appendix or implementation plan is not a mandate: it is planning."},
	{"Laws and regulations the work must keep within", "Risks of type constraint", "Not a mandate unless the document says it authorises the work."},
	{"An escalation route", "Project.escalationRoute (or Programme's)", "The bodies a matter goes up through, nearest first, above the project's own manager and team (who are not on it). Where the document writes the route out, it is that route as written. Otherwise a body that gives direction is on it; one that only receives reports is not. \"X/Y\" is one body, named as written, and the same Resource wherever X or Y appears alone (as an issuer)."},
	{"Owners named as units", "A role or unit Resource", "Where a field asks who (an owner, a verifier, who confirms), name the role that answers; a unit that answers as a whole as its orgUnit Resource. Several with none marked as lead: the first named, the others in the KPI's definition or the notes under that step's key. A person named: the role the document gives them, else a role named for what they do; with a post and a project role, the post is the Resource and the project role is the position in the project's resources. Never a team, never a person. An aim with no owner stated: the sponsor's role. A benefits plan's owners own its benefits, not the aims."},
	{"Roles and bodies a definition names", "Resource, defined before the goal, project, programme or KPI that names them", "A project's own positions then go in its resources, each pointing at its Resource; every Resource declared should be named somewhere (checks lists those nothing names)."},
	{"Names and acronyms", "As the document writes them", "Never expand an acronym from outside knowledge; the person can."},
	{"A service the document does not name", "Operation, status planned, named by what it does", "Such as \"<policy> compliance monitoring\"; its mandate the policy instrument the running work is under; status planned until the running work has started, even when the policy is in force; its service owner the first unit or role the document gives the running work to."},

	// Risk.
	{"Risks", "Risks of type risk, with impact, likelihood, mitigation and owner", ""},
	{"Issues already happening", "Risks of type issue", ""},
	{"Critical dependencies", "Risks of type dependency, with depends naming what is waited on", "Something someone must deliver to the work. depends: direction needs, on naming who delivers it, inside the organisation or not (a Resource by kind and id, a role in resources by local, else external), needed when the work needs it, as a timing: a month, a window, or after one of the project's own milestones (the milestone the work needing it starts at). Its mitigation from the risk row about the same party or thing (with two, the one whose risk is the dependency failing); a risk row that is itself a dependency is that dependency, recorded once, or one per party when it names several joined by \"and\" or a comma (\"X/Y\" is one party, as everywhere); a risk row typed risk stays a risk even when a dependency borrows its mitigation. needed only when the document dates the need. A gate the project meets with its own deliverables is not a dependency: it is the order of tasks. With no matching row, leave risks-mitigation open for your person."},
	{"Constraints and fixed external dates", "Risks of type constraint", "A fixed limit the work lives within; no mitigation. One that repeats a risk or dependency already recorded (the same cause, named as the cause there) is not recorded again."},
	{"Key assumptions of the results logic", "Assumption, named by the success criteria that rest on them", "A belief about how people or bodies will respond to the outputs, which the chain from outputs to outcomes rests on (suppliers keep reformulating, staff use the training). A thing someone must deliver is a dependency, a date or resource holding is a schedule risk: each is recorded once, never as both."},
	{"Schedule and context assumptions (dates hold, funding stays, people stay available)", "Risks of type risk, the assumption failing as the risk", "Not an Assumption: those are the results logic's. Its mitigation is the document's general rule for changed conditions where it gives one; impact and likelihood only as scored, else risks-placed is left open."},
	{"Escalation with no target stated", "escalate.to: the next body on the escalation route above the work", "With no route, the sponsor."},
	{"Escalation only if something slips", "escalate.flag false, the trigger in the mitigation", "Flag only what is escalated now."},
	{"Uncosted or unfunded needs", "Risks of type issue, escalated to whoever decides funding", "A funding line once costed."},

	// Money and data.
	{"Funding status", "funding status: approved when the document calls the money approved, whatever body noted it; requested when it is only noted, pending or asked for; unfunded when none is found", "A condition on it goes in the notes under the step key resources."},
	{"A budget head with no holder named", "FundingSource.heldBy left unset", "code is the head as written."},
	{"A service's recurrent costs", "Operation.funding, per month or year", "Never on the project that sets it up. Uncosted: an issue on the project's risks, and landing-service-funding left open with that reason."},
	{"A budget broken down by cost line", "Project.costs, one line per cost line, and one funding line per source", "Funding states the money and its source; costs say what it pays for. An unfunded line names the condition that decides it."},
	{"Data sources kept outside the organisation", "DataSource.keptBy, provenance external", "team stays your own team that reads it. provenance says who runs the source: internal when any unit of the organisation runs it, even jointly, external otherwise; keptBy names the outside body that keeps it, when the document names one."},
	{"How a data source is captured, classified or categorised", "DataSource.capture, .classification, .category", "Only as the document states, from its own word for the kind of store; left unset otherwise."},
	{"Personal data in what a project produces", "The project's data.produces: personalData, set from what the output holds by the guide's three levels", "The document need not state it: records of named people (an operator, a trainee) are personal, about children or health sensitive, records about sites, products or counts none."},
	{"Reporting termly or per survey wave", "A reporting cycle of named periods", "Each by the month it ends. A frequency tied to a term (\"quarterly in Term III\") is named periods ending in the months the document gives. A frequency with no start month: the month the work starts, said in the cycle's name or the notes. A frequency inside a term with no months given: one period, ending in the month the term ends. A year (academic, financial) ends in the month the document says it does, else the month its last term ends. An approximate date (\"about 12 months\") is the month it lands on, counted from the date given, or from the end of a window given (a term). dueOffsetDays only as stated."},
	{"Stakeholders", "StakeholderMap entries", "One entry per party: a beneficiary group as group, anyone else as a resource; a group and the body that represents it are two entries. \"X / Y\" is two entries; \"X (A, B, C)\" is one, X, unless A, B or C is named elsewhere in the document on its own. Small operators and vendors the work trains or serves are a BeneficiaryGroup; companies it asks to change products are resources, and so is their association (tier as theirs). A unit the document does not place is an orgUnit Resource named as written. tier primary for the beneficiaries (primary and secondary alike) and those the work obliges to comply, companies asked to change products included; secondary for everyone else, partners who carry the work included, whatever the document calls them. Influence and interest only as the document scores them; their stake and relationship owner from its engagement plan."},

	// Out.
	{"Decision log, change log", "Not ported", "Running the work: Cartograph keeps its own versions and change sets. A decision that authorises the work is a mandate."},
	{"Action log, and actions open before approval", "Project.conditions: the action, the role that owns it, when it is due, what it gates", "Only actions the approval depends on; the rest are running the work."},
	{"RACI matrix", "Project.responsibilities, one row per decision or deliverable", "Roles of this project's resources, one accountable per row; never people."},
	{"Reporting plan, status ratings, readiness assessment, a critical path in words", "Not ported", "Cartograph reads readiness from its checks and the critical path from the schedule; a document's own grades are never retyped."},
	{"Sign-off table", "Project.signOffs, one line per stage and role", "A signature is recorded as an event when it is given."},
	{"Procurement plan", "Project.procurement, one item per requirement", "Its value, method, lead time, owner and when it is needed."},
	{"Staffing quantities, time commitments", "Not ported", "Planning; a role the work needs is a resource."},
	{"Prose a template asks for (implementation approach, equity, legal and safeguarding, evaluation design, status rules)", "The notes under the nearest step key, a sentence or two", "Never retyped as the charter's text: the charter is generated from fields and is a few pages. Where a field holds part of it (personal data, a stakeholder, a cost, a risk, a success criterion), use the field."},
	{"Long descriptions in a register (deliverables, risks, milestones)", "A name of a few words; a description of one sentence at most", "The charter prints names; detail stays in Cartograph."},
	{"Evaluation questions", "Not ported", "The document's; the measures that answer them are KPIs or success criteria."},
	{"Decision rights and scope change authority", "The notes under the step key resources", "Who decides what is governance: the escalation route and mandates hold what Cartograph checks."},
	{"The project's current stage and phase statuses", "Not ported", "Progress is the delivery tool's."},
	{"Delivery model and evaluation design", "The notes under the step key goals", "Never a field of its own."},
	{"Closure criteria", "Success criteria atClosing", "A closure criterion that a running service meets (monitoring embedded in operations) is atLanding. Lessons learned are not ported."},
	{"What engagement a stakeholder needs (\"formal transmission\", \"quarterly engagement\")", "The entry's stake: what they care about, then what the work needs from them, in one sentence", "Channels and timing are the communications plan's."},
	{"Strategic alignment, rationale, why now, options considered", "The project's notes under the step key goals", "The goal's whyItMatters is the impact evidence (see above) when there is any, else the alignment in one sentence."},
	{"Earlier initiatives the work builds on", "The project's notes under the step key goals", "A running one is an Operation; a project still in the workspace is named in scopeOut or as a dependency."},
	{"Readiness gates (what must be true before a date)", "Dependencies (risks of type dependency) with needed", "Each names what is waited on."},
	{"A stakeholder engagement plan's channels and timing", "Not ported", "The communications plan's, not the definition's."},
	{"A portfolio the document names but does not define", "The project's notes under the step key goals", "No Portfolio without its objectives."},
}
